on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      issue_id:
        description: 'Issue ID'     
        required: false
      version:
        description: 'Version'     
        required: false

name: Add comment to issue

jobs:
  comment:
    name: Add comment
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repo
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: Set commitish
        run: |
          ls -ltr
          output="$(git log --pretty=format:'%H' -1)"
          echo "::set-output name=commitish::`echo $(git log --pretty=format:'%H' -1)`"
        id: commit-hash
      - name: Get Commit Hash
        run: echo "Commit Hash ${{ steps.commit-hash.outputs.commitish }}"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.inputs.issue_id }}
          body: |
            INFO
            - Version: ${{ github.event.inputs.version }}
            - Commit Hash: ${{ steps.commit-hash.outputs.commitish }}
            - Commented on Issue Id: ${{ github.event.inputs.issue_id }}


            
