on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      issue_id:
        description: 'Issue ID'     
        required: false
      version:
        description: 'Version'     
        required: false

name: Add comment to issue

jobs:
  comment:
    name: Add comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set commitish
        run: |
          ls -ltr
          git pull origin main
          echo "::set-output name=commitish::`echo $(git log --pretty=format:'%H' -1)`"
        id: commit-hash
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Get component versions
        run: |
          echo "::set-output name=versions::`echo $(python test.py)`"
        id: version-info
      - name: Print
        run: |
          echo "Commit Hash ${{ steps.commit-hash.outputs.commitish }}"
          echo "Version ${{ steps.version-info.outputs.versions }}"
      - name: Read version_info.txt
        id: version_info
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version_info.txt
      - name: Echo version_info.txt
        run: echo "${{ steps.version_info.outputs.content }}"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.inputs.issue_id }}
          body: |
            INFO
            - Version: ${{ github.event.inputs.version }}
            - Commit Hash: ${{ steps.commit-hash.outputs.commitish }}
            - Commented on Issue Id: ${{ github.event.inputs.issue_id }}
            - Other info
            ${{ steps.version-info.outputs.versions }}
            - https://github.com/YogeshJain96/gohugo/commit/${{ steps.commit-hash.outputs.commitish }}
            ${{ steps.version_info.outputs.content }}


            
