name: Update md files Test

on:
  # push:
  # schedule:
  #  - cron: "*/5 * * * *" # Run every 5 mins
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout test-api repo
        uses: actions/checkout@v2 # checkout the repository content to github runner
        with:
          repository: YogeshJain96/test-api
          path: main

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run py-script to get the latest data
        run: main.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update MD files as per API response" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
