on: 
  workflow_dispatch:
  push:
    branches:
      - main

name: Send Release Version & Issue ID
jobs:
  get-latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "call action"
      id: last_release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ github.token }}
        exclude_types: "draft"
        view_top: 1
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: update_source.yml
    - name: "Print TAG NAME"
      run: |
        echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
        cat issue_id_file/issue_id.txt
        echo ${{ github.sha }}
        echo get log info
        git log --pretty=format:'%H' -1
    # delete-artifact
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: issue_id_file
