on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.1
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      commitish:
        description: 'Commit Hash'     
        required: false
      tagName:
        description: 'Tag Name'     
        required: true

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: printInputs
        run: |
          echo "Commit Hash: ${{ github.event.inputs.commitish }}"
          echo "Tag Name: ${{ github.event.inputs.tagName }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        if: ${{ github.event.inputs.commitish  == ''  }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: Release ${{ github.event.inputs.tagName }}
          tag_name: ${{ github.event.inputs.tagName }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Create Release with commitish
        if: ${{ github.event.inputs.commitish  != '' }}
        id: create_release_commitish
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: Release ${{ github.event.inputs.tagName }}
          tag_name: ${{ github.event.inputs.tagName }}
          commitish: ${{ github.event.inputs.commitish }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
