name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    if: contains(toJson(github), 'run-test')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Script
      run: echo toJson(github)
  
